### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by zzy0990** [drakeet/LabelView#1]
如果上下左右还能设置颜色或者字体大小就更完美了。

**Comment by easternHong** [comment]
按照LabelView的实现方式,字符串是append,使不能实现颜色,大小,字体属性的.

**Comment by drakeet** [comment]
我可以做到~ 待我之后更新实现

**Comment by xu6148152** [comment]
用Span就好了，有什么实现不了的。还有StaticLayout等着你去用。
然而我并没有发现这个东西的需求在哪里。

**Comment by drakeet** [comment]
![t z80z9v kb6mx2p a5x5](https://cloud.githubusercontent.com/assets/5214214/10749691/4fdd59c2-7ca8-11e5-9a05-2d8ca78f0124.jpg)
